# Site
repository: Srijith97/modern-resume-theme

# Content configuration version
version: 2

# Personal info
name: Saisrijith Reddy Maramreddy
title: Data Scientist | Python • R • SQL
email: shrey.maramreddy@gmail.com
phone: (929) 305-8774
website: https://github.com/Srijith97

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username: Srijith97
linkedin_username: saisrijith-reddy-maramreddy-399869166

# About Section
about_profile_image: images/profile.jpg  # Optional: upload an image to this path
about_content: |
  I am a data analyst currently pursuing a Master’s in Statistics at Zicklin School of Business, with a strong foundation in machine learning, statistical modeling, and data-driven decision-making.

  My coursework and projects reflect deep experience in regression, multivariate methods, and advanced data mining using Python, R, and SQL. I am actively seeking roles in data science, statistical modeling, and quantitative research.

  My goal is to apply analytical thinking and technical expertise to solve real-world business problems and drive impact in data-intensive environments.


# Content Sections
content:
  - title: Experience
    layout: list
    content:
      - layout: right
        title: BCITS Pvt Ltd
        sub_title: Data Analyst Intern
        caption: Sept 2022 – July 2023
        description: |
          - Led data cleansing and predictive modeling for Smart City Solutions
          - Improved billing accuracy by 15% and customer satisfaction by 20%
          - Built dashboards for KPI monitoring using R and Excel

      - layout: right
        title: Augment Softsol
        sub_title: Management Trainee
        caption: July 2015 – July 2016
        description: |
          - Managed recruitment for technical roles and evaluated SaaS tools
          - Partnered with IT and Finance to reduce licensing costs by 10%

  - title: Education
    layout: list
    content:
      - layout: right
        title: Zicklin School of Business, NY
        sub_title: MS in Statistics
        caption: Expected Dec 2025
        description: |
          GPA (current): 3.93  
          Relevant coursework: Regression Analysis, Statistical Inference, Multivariate Methods, Machine Learning, Data Mining, Advanced Data Analysis, Probability


      - layout: right
        title: Imperial College Business School, London
        sub_title: MS in Investment & Wealth Management
        caption: Sept 2021 – Sept 2022
        description: |
          Project: Evaluated Microsoft's acquisition of Pinterest using valuation models

      - layout: right
        title: Pennsylvania State University
        sub_title: BS in Industrial Engineering
        caption: Aug 2016 – May 2020
        description: |
          GPA: 3.83  
          Dean’s List (All Semesters)

  - title: Certifications
    layout: list
    content:
      - layout: left
        title: Python Bootcamp – Udemy
        description: |
          Mastered OOP and timestamp manipulation in Python.

      - layout: left
        title: Python for ML & Data Science – Udemy
        description: |
          Built regression, NLP, and clustering models using Pandas, Scikit-learn, and Seaborn.

      - layout: left
        title: Finance Data with Python & Pandas – Udemy
        description: |
          Worked with CAPM, Sharpe Ratio, and MPT for portfolio optimization.

  - title: Skills
    layout: text
    content: |
      - Python, R, SQL, SAS, Excel
      - Machine Learning, Statistical Analysis, Predictive Modeling
      - Data Visualization, Financial Modeling
      - Bloomberg Terminal, Capital IQ
      - Team Leadership, Cross-functional Communication

# Footer
footer_show_references: true
references_title: References available on request

# Theme and Build settings
remote_theme: sproogen/modern-resume-theme
sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
]
